---
kind: pipeline
type: docker
name: default

trigger:
  branch:
  - jupyter-notebook-daisy

steps:
- name: prepare-tags
  image: busybox:1.32
  when:
    event:
    - push
  environment:
    BASE_VERSION: 'python-3.8.8'
  commands:
  - echo -n "1,1-$${BASE_VERSION}" > .tags

- name: publish-image-1
  image: plugins/docker
  when:
    event:
    - push
  settings:
    debug: true 
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    context: jupyter-notebooks/daisy/
    dockerfile: jupyter-notebooks/daisy/Dockerfile
    repo: opertusmundi/daisy-notebook
    mirror: http://registry-mirror:5000

