---
kind: pipeline
type: docker
name: default

trigger:
  branch:
  - gdal-python-builder

steps:
- name: prepare-tags
  image: busybox:1.32
  when:
    event:
    - push
  environment:
    # version of the packaged application (GDAL)
    APP_VERSION: '3.1'
  commands:
  - echo -n "1-$${APP_VERSION}" > .tags

- name: build-and-publish
  image: plugins/docker
  when:
    event:
    - push
  settings:
    debug: true 
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    context: gdal-python-builder
    dockerfile: gdal-python-builder/Dockerfile
    repo: opertusmundi/gdal-python-builder
    mirror: http://registry-mirror:5000

