---
kind: pipeline
type: docker
name: default

trigger:
  branch:
  - rsyslog-with-logrotate

steps:
- name: prepare-tags
  image: busybox:1.32
  when:
    event:
    - push
  environment:
    # version of the packaged application (rsyslog)
    APP_VERSION: '8.2012.0'
  commands:
  - echo -n "1,1-$${APP_VERSION}" > .tags

- name: build-and-publish
  image: plugins/docker
  when:
    event:
    - push
  settings:
    debug: true 
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    context: pgpool
    dockerfile: rsyslog-with-logrotate/Dockerfile
    repo: opertusmundi/rsyslog-with-logrotate
    mirror: http://registry-mirror:5000

