---
kind: pipeline
type: docker
name: default

trigger:
  branch:
  - java-commons-builder

steps:

- name: build-and-publish
  image: plugins/docker
  when:
    event:
    - push
  settings:
    debug: true 
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    context: java-commons-builder
    dockerfile: java-commons-builder/Dockerfile
    repo: opertusmundi/java-commons-builder
    tags:
    - '1'
    - '1.1'
    mirror: http://registry-mirror:5000

