---
kind: pipeline
type: docker
name: default

trigger:
  branch:
  - keycloak

steps:

- name: checkout-submodules
  image: alpine/git:v2.30.1
  when:
    event:
    - push
  commands:
  - git submodule init
  - git submodule update keycloak/themes
  - git submodule status

- name: prepare-tags
  image: busybox:1.32
  when:
    event:
    - push
  environment:
    # version of the packaged application (Keycloak)
    APP_VERSION: '15.0.2'
  commands:
  - echo -n "1-$${APP_VERSION}" > .tags

- name: build-and-publish
  image: plugins/docker
  when:
    event:
    - push
  settings:
    debug: true 
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    context: keycloak/
    dockerfile: keycloak/Dockerfile
    repo: opertusmundi/keycloak
    mirror: http://registry-mirror:5000

