# https://github.com/keycloak/keycloak-containers/blob/15.0.2/server/README.md
FROM quay.io/keycloak/keycloak:15.0.2

# https://github.com/keycloak/keycloak-containers/blob/15.0.0/server/README.md#adding-a-custom-theme
COPY themes/ /opt/jboss/keycloak/themes/


